### ISSUE TITLE
Hot fix lỗi crash app khi vào phần biểu đồ

### ISSUE THREAD

**Issue by KhacLuyen99** [CnpmLanKit/SEO3-Group10#20]

**Comment by KhacLuyen99** [comment]
Ai biết tư dưng lỗi app khi vô phần chart ko ?

**Comment by KhacLuyen99** [comment]
Không hiểu sao hqua vẫn bình thường mà nay tư dưng bị

**Comment by KhacLuyen99** [comment]
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at java.text.SimpleDateFormat.parseInternal(SimpleDateFormat.java:1563)
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1550)
        at java.text.DateFormat.parse(DateFormat.java:360)
        at a2dv606.androidproject.MainWindow.DateHandler.dayFormat(DateHandler.java:46)
        at a2dv606.androidproject.Chart.ChartActivity.onCreate(ChartActivity.java:55)

**Comment by DinhNam99** [comment]
Ừ để xem thử

**Comment by KhacLuyen99** [comment]
Lỗi NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference đấy

**Comment by KhacLuyen99** [comment]
Hay hqua có ai làm gì ko ?

**Comment by KevilTtc** [comment]
vẫn ok mà.fix dc chưa

**Comment by KevilTtc** [comment]
lỗi phần tgian đấy. kiểu bắt đầu ngày mới nó chưa reset tgian và cập nhập vào chart nên bị lỗi đấy

**Comment by KhacLuyen99** [comment]
ukm, t biết vấn đề rồi đấy

**Comment by KhacLuyen99** [comment]
vì ứng dụng của mk có dữ liệu của ngày hqua trong khi đó phần biểu đồ của mk ngày hnay thi chưa có dữ liệu khi mk vào request nó sẽ trả ra null mà mk chưa validate nên lỗi là phải.

**Comment by KhacLuyen99** [comment]
T mới sử lý phần check validate rồi nên h sẽ ko bị sao nữa nhé

**Comment by KhacLuyen99** [comment]
T mới push code lên ae tham khảo đi nhé
